<?php
/** op-skeleton-2023:/www/index.phtml
 *
 * @created		2023-12-29
 * @version		1.0
 * @package		op-app-skeleton-2023
 * @author		Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright	Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 */
namespace OP;

//	...
OP()->App()->Title('TOP')

?>
<article id="top">
	<div data-translate="true" data-language="en">
		<h1>Welcome to onepiece-framework.com</h1>
		<p>
			The onepiece-framework is insanely great!!
			This is very intuitive design.
			Our before framework will obsolete.
			This framework will destructive innovators.
		</p>
	</div>
	<script>
	document.addEventListener('DOMContentLoaded', async function(){

	document.querySelectorAll('[data-translate="true"]').forEach( async function(element){
		const lang = element.getAttribute('data-language');
		const html = element.innerHTML;
		const tran = await $OP.Translate.Fetch(html);
		element.innerHTML = tran;
	});

	//	const test = $OP.Translate.Fetch('This is a new World.');
	});
	</script>
</article>
<section>
	<h1 data-translate="true">Please choose your use language</h1>

	<!-- Display area -->
	<ul class="translate language list" id="<?= OP()->Config('translate')['language_area_id'] ?>"></ul>

	<!-- Template tag -->
	<template><li class="" data-lang=""></li></template>

	<!-- JavaScript -->
	<script>
	document.addEventListener('DOMContentLoaded', async function(){
		//	...
		const json = await $OP.Translate.Language.Fetch('https://api.onepiece-framework.com/i18n/translate/language/list/');

		//	...
		$OP.Translate.Language.Display(json);
		$OP.Translate.Language.Event();
	});
	</script>
	<?php
	Unit::Load('Translate');
//	OP()->Unit('Translate')->Language()->List('html');
	?>
</section>
