<?php
/** op-skeleton-2023:/www/index.phtml
 *
 * @created		2023-12-29
 * @version		1.0
 * @package		op-app-skeleton-2023
 * @author		Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright	Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 */
namespace OP;

?>
<article id="top">
	<div data-i18n="true" data-i18n-locale="en">
		<h1>Welcome to onepiece-framework.com</h1>
		<p>
			The onepiece-framework is insanely great!!
			This is very intuitive design.
			Our before framework will obsolete.
			This framework will destructive innovators.
		</p>
	</div>
</article>
<section>
	<h1 data-translate="true">Please choose your use language</h1>
	<?php OP()->Unit('Translate')->Language()->List('html') ?>
</section>
